-- MySQL Script generated by MySQL Workbench
-- Thu Sep 24 15:44:57 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema maison_rosalie
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema maison_rosalie
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `maison_rosalie` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `maison_rosalie` ;

-- -----------------------------------------------------
-- Table `maison_rosalie`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `maison_rosalie`.`categories` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(80) NOT NULL,
  `slug` VARCHAR(100) NOT NULL,
  `description` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uq_categories_title` (`title` ASC) VISIBLE,
  UNIQUE INDEX `uq_categories_slug` (`slug` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `maison_rosalie`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `maison_rosalie`.`users` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(50) NOT NULL,
  `email` VARCHAR(254) NOT NULL,
  `password_hash` VARCHAR(255) NOT NULL,
  `role` ENUM('user', 'admin') NOT NULL DEFAULT 'user',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uq_users_username` (`username` ASC) VISIBLE,
  UNIQUE INDEX `uq_users_email` (`email` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `maison_rosalie`.`recipes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `maison_rosalie`.`recipes` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(150) NOT NULL,
  `slug` VARCHAR(170) NOT NULL,
  `description` TEXT NOT NULL,
  `main_image` VARCHAR(500) NOT NULL,
  `prep_time_minutes` INT UNSIGNED NOT NULL,
  `cook_time_minutes` INT UNSIGNED NOT NULL,
  `portions` INT UNSIGNED NOT NULL,
  `difficulty` ENUM('easy', 'medium', 'hard') NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `author_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uq_recipes_slug` (`slug` ASC) VISIBLE,
  INDEX `idx_recipes_author` (`author_id` ASC) VISIBLE,
  INDEX `idx_recipes_created_at` (`created_at` ASC) VISIBLE,
  CONSTRAINT `fk_recipes_author`
    FOREIGN KEY (`author_id`)
    REFERENCES `maison_rosalie`.`users` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `maison_rosalie`.`comments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `maison_rosalie`.`comments` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `author_id` INT UNSIGNED NOT NULL,
  `recipe_id` INT UNSIGNED NOT NULL,
  `subject` VARCHAR(120) NULL DEFAULT NULL,
  `message` VARCHAR(500) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `status` ENUM('pending', 'published', 'hidden') NOT NULL DEFAULT 'published',
  PRIMARY KEY (`id`),
  INDEX `idx_comments_recipe_date` (`recipe_id` ASC, `created_at` ASC) VISIBLE,
  INDEX `idx_comments_author_date` (`author_id` ASC, `created_at` ASC) VISIBLE,
  CONSTRAINT `fk_comments_author`
    FOREIGN KEY (`author_id`)
    REFERENCES `maison_rosalie`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_comments_recipe`
    FOREIGN KEY (`recipe_id`)
    REFERENCES `maison_rosalie`.`recipes` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `maison_rosalie`.`contact_messages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `maison_rosalie`.`contact_messages` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `email` VARCHAR(254) NOT NULL,
  `subject` VARCHAR(120) NOT NULL,
  `message` VARCHAR(2000) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `idx_contact_messages_date` (`created_at` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `maison_rosalie`.`ingredients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `maison_rosalie`.`ingredients` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(120) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uq_ingredients_name` (`name` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

-- -----------------------------------------------------
-- Table `maison_rosalie`.`ratings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `maison_rosalie`.`ratings` (
  `user_id` INT UNSIGNED NOT NULL,
  `recipe_id` INT UNSIGNED NOT NULL,
  `rating` TINYINT UNSIGNED NOT NULL,
  `rated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`user_id`, `recipe_id`),
  INDEX `idx_ratings_recipe` (`recipe_id` ASC) VISIBLE,
  CONSTRAINT `fk_ratings_recipe`
    FOREIGN KEY (`recipe_id`)
    REFERENCES `maison_rosalie`.`recipes` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_ratings_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `maison_rosalie`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `maison_rosalie`.`recipe_categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `maison_rosalie`.`recipe_categories` (
  `recipe_id` INT UNSIGNED NOT NULL,
  `category_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`recipe_id`, `category_id`),
  INDEX `idx_recipe_categories_category` (`category_id` ASC) VISIBLE,
  CONSTRAINT `fk_recipe_categories_category`
    FOREIGN KEY (`category_id`)
    REFERENCES `maison_rosalie`.`categories` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_recipe_categories_recipe`
    FOREIGN KEY (`recipe_id`)
    REFERENCES `maison_rosalie`.`recipes` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `maison_rosalie`.`recipe_ingredients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `maison_rosalie`.`recipe_ingredients` (
  `recipe_id` INT UNSIGNED NOT NULL,
  `ingredient_id` INT UNSIGNED NOT NULL,
  `quantity` DECIMAL(10,3) NULL DEFAULT NULL,
  `unit` VARCHAR(40) NULL DEFAULT NULL,
  PRIMARY KEY (`recipe_id`, `ingredient_id`),
  INDEX `idx_recipe_ingredients_ingredient` (`ingredient_id` ASC) VISIBLE,
  CONSTRAINT `fk_recipe_ingredients_ingredient`
    FOREIGN KEY (`ingredient_id`)
    REFERENCES `maison_rosalie`.`ingredients` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_recipe_ingredients_recipe`
    FOREIGN KEY (`recipe_id`)
    REFERENCES `maison_rosalie`.`recipes` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `maison_rosalie`.`steps`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `maison_rosalie`.`steps` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `recipe_id` INT UNSIGNED NOT NULL,
  `step_number` INT UNSIGNED NOT NULL,
  `title` VARCHAR(120) NOT NULL,
  `description` TEXT NOT NULL,
  `image` VARCHAR(500) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uq_steps_recipe_number` (`recipe_id` ASC, `step_number` ASC) VISIBLE,
  CONSTRAINT `fk_steps_recipe`
    FOREIGN KEY (`recipe_id`)
    REFERENCES `maison_rosalie`.`recipes` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
